Verifying sv/ldv-validator-v0.8/linux-stable-5742d35-1-136_1a-drivers--usb--serial--ti_usb_3410_5052.ko-entry_point_ldv-val-v0.8_false-unreach-call.cil.out.c
main using GenerateFunctionCallPreprocessor ...
GenerateFunctionCallPreprocessor parents for __VERIFIER_error:
__VERIFIER_error
  ldv_error
    ldv_usb_serial_deregister
      ldv_usb_serial_deregister_5
        ti_exit
          main
          <end>
      ldv_usb_serial_deregister_4
        ti_exit
          main
          <end>
      ldv_usb_serial_deregister_3
        ti_init
          main
          <end>
      ldv_usb_serial_deregister_2
        ti_init
          main
          <end>
