Verifying sv/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--net--ethernet--via--via-rhine.ko-entry_point_true-unreach-call.cil.out.c
main using GenerateFunctionCallPreprocessor ...
GenerateFunctionCallPreprocessor parents for __VERIFIER_error:
__VERIFIER_error
  ldv_error
    ldv_check_alloc_nonatomic
    <end>
    ldv_check_alloc_flags_and_return_some_page
    <end>
    ldv_check_alloc_flags
      ldv_skb_clone_41
      <end>
      ldv_pskb_expand_head_40
      <end>
      ldv_pskb_expand_head_39
      <end>
      ldv___netdev_alloc_skb_38
        __netdev_alloc_skb_ip_align
          netdev_alloc_skb_ip_align
            rhine_rx
              rhine_napipoll
                rhine_init_one_common
                  rhine_init_one_pci
                    main
                    <end>
                  rhine_init_one_platform
                    main
                    <end>
      ldv___netdev_alloc_skb_37
      <end>
      ldv___netdev_alloc_skb_36
        netdev_alloc_skb
          rhine_skb_dma_init
            rhine_rx
              rhine_napipoll
                rhine_init_one_common
                  rhine_init_one_pci
                    main
                    <end>
                  rhine_init_one_platform
                    main
                    <end>
            alloc_rbufs
              rhine_open
                main
                <end>
      ldv_skb_copy_35
      <end>
      ldv_skb_clone_33
      <end>
      ldv_pskb_expand_head_31
      <end>
      ldv_kmem_cache_alloc_25
      <end>
