Verifying sv/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--net--ethernet--dec--tulip--dmfe.ko-entry_point_true-unreach-call.cil.out.c
main using GenerateFunctionCallPreprocessor ...
GenerateFunctionCallPreprocessor parents for __VERIFIER_error:
__VERIFIER_error
  ldv_error
    ldv_check_alloc_nonatomic
    <end>
    ldv_check_alloc_flags_and_return_some_page
    <end>
    ldv_check_alloc_flags
      ldv_skb_clone_36
      <end>
      ldv_pskb_expand_head_35
      <end>
      ldv_pskb_expand_head_34
      <end>
      ldv___netdev_alloc_skb_33
      <end>
      ldv___netdev_alloc_skb_32
      <end>
      ldv___netdev_alloc_skb_31
        netdev_alloc_skb
          allocate_rx_buffer
            dmfe_descriptor_init
              dmfe_init_dm910x
                dmfe_dynamic_reset
                  dmfe_timer
                    dmfe_open
                      main
                      <end>
                dmfe_open
                  main
                  <end>
                dmfe_resume
                  main
                  <end>
                  main
                  <end>
                  main
                  <end>
            dmfe_interrupt
              dmfe_open
                main
                <end>
              poll_dmfe
                main
                <end>
                main
                <end>
                main
                <end>
              ldv_irq_1
                choose_interrupt_1
                  main
                  <end>
                choose_interrupt_1
                choose_interrupt_1
                choose_interrupt_1
          dmfe_rx_packet
            dmfe_interrupt
              dmfe_open
              poll_dmfe
              ldv_irq_1
                choose_interrupt_1
                choose_interrupt_1
                choose_interrupt_1
                choose_interrupt_1
      ldv_skb_copy_30
      <end>
      ldv_skb_clone_28
      <end>
      ldv_pskb_expand_head_26
      <end>
      ldv_kmem_cache_alloc_20
      <end>
