Verifying sv/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--usb--class--cdc-acm.ko-entry_point_true-unreach-call.cil.out.c
main using GenerateFunctionCallPreprocessor ...
GenerateFunctionCallPreprocessor parents for __VERIFIER_error:
__VERIFIER_error
  ldv_error
    ldv_check_alloc_nonatomic
    <end>
    ldv_check_alloc_flags_and_return_some_page
    <end>
    ldv_check_alloc_flags
      kmalloc
        acm_probe
          main
          <end>
        acm_probe
          main
          <end>
      ldv_usb_submit_urb_39
        acm_resume
          acm_reset_resume
            main
            <end>
          main
          <end>
      ldv_usb_alloc_urb_37
        acm_probe
          main
          <end>
      ldv_usb_alloc_urb_36
        acm_probe
          main
          <end>
      ldv_usb_alloc_coherent_35
        acm_probe
          main
          <end>
      ldv_usb_alloc_urb_34
        acm_probe
          main
          <end>
      ldv_usb_alloc_coherent_33
        acm_probe
          main
          <end>
      ldv_usb_alloc_coherent_32
        acm_write_buffers_alloc
          acm_probe
            main
            <end>
      ldv_usb_submit_urb_31
        acm_port_activate
      ldv_usb_submit_urb_30
        acm_submit_read_urb
          acm_submit_read_urbs
            acm_port_activate
            acm_tty_unthrottle
            acm_resume
              acm_reset_resume
          acm_read_bulk_callback
            acm_probe
            acm_probe
      ldv_usb_submit_urb_29
        acm_ctrl_irq
      ldv_usb_submit_urb_28
        acm_start_wb
          acm_tty_write
          acm_resume
            acm_reset_resume
      ldv_kmem_cache_alloc_25
      <end>
