Verifying sv/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--net--ethernet--amd--amd8111e.ko-entry_point_true-unreach-call.cil.out.c
main using GenerateFunctionCallPreprocessor ...
GenerateFunctionCallPreprocessor parents for __VERIFIER_error:
__VERIFIER_error
  ldv_error
    ldv_check_alloc_nonatomic
    <end>
    ldv_check_alloc_flags_and_return_some_page
    <end>
    ldv_check_alloc_flags
      ldv_skb_clone_36
      <end>
      ldv_pskb_expand_head_35
      <end>
      ldv_pskb_expand_head_34
      <end>
      ldv___netdev_alloc_skb_33
      <end>
      ldv___netdev_alloc_skb_32
      <end>
      ldv___netdev_alloc_skb_31
        netdev_alloc_skb
          amd8111e_rx_poll
            amd8111e_probe_one
              main
              <end>
          amd8111e_init_ring
            amd8111e_restart
              amd8111e_resume
                main
                <end>
                main
                <end>
                main
                <end>
              amd8111e_tx_timeout
                main
                <end>
                main
                <end>
                main
                <end>
              amd8111e_open
                main
                <end>
              amd8111e_change_mtu
                main
                <end>
                main
                <end>
      ldv_skb_copy_30
      <end>
      ldv_skb_clone_28
      <end>
      ldv_pskb_expand_head_26
      <end>
      ldv_kmem_cache_alloc_20
      <end>
