Verifying sv/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-08_1a-drivers--media--pci--pt3--earth-pt3.ko-entry_point_false-unreach-call.cil.out.c
main using GenerateFunctionCallPreprocessor ...
GenerateFunctionCallPreprocessor parents for __VERIFIER_error:
__VERIFIER_error
  ldv_error
    ldv_module_put
      ldv_module_put_and_exit
      <end>
      ldv_module_put_10
        pt3_cleanup_adapter
          pt3_remove
            main
            <end>
          pt3_probe
            main
            <end>
      ldv_module_put_9
        pt3_cleanup_adapter
          pt3_remove
            main
            <end>
          pt3_probe
            main
            <end>
      ldv_module_put_8
        pt3_attach_fe
          pt3_probe
            main
            <end>
      ldv_module_put_7
        pt3_attach_fe
          pt3_probe
            main
            <end>
    ldv_check_final_state
      main
      <end>
