Verifying sv/ldv-consumption/32_7a_cilled_true-unreach-call_linux-3.8-rc1-32_7a-drivers--usb--host--r8a66597-hcd.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c
main using GenerateFunctionCallPreprocessor ...
GenerateFunctionCallPreprocessor parents for __VERIFIER_error:
__VERIFIER_error
  ldv_error
    ldv_atomic_dec_and_mutex_lock_mutex
    <end>
    ldv_mutex_lock_killable_mutex
    <end>
    ldv_mutex_lock_interruptible_mutex
    <end>
    ldv_atomic_dec_and_mutex_lock_lock
    <end>
    ldv_mutex_trylock_lock
    <end>
    ldv_mutex_lock_killable_lock
    <end>
    ldv_mutex_lock_interruptible_lock
    <end>
    ldv_atomic_dec_and_mutex_lock_cred_guard_mutex
    <end>
    ldv_mutex_trylock_cred_guard_mutex
    <end>
    ldv_mutex_lock_killable_cred_guard_mutex
    <end>
    ldv_mutex_lock_interruptible_cred_guard_mutex
    <end>
    ldv_mutex_unlock_mutex
      ldv_mutex_unlock_7
      <end>
    ldv_mutex_trylock_mutex
      ldv_mutex_trylock_6
      <end>
    ldv_mutex_lock_mutex
      ldv_mutex_lock_5
      <end>
    ldv_mutex_unlock_cred_guard_mutex
      ldv_mutex_unlock_4
      <end>
    ldv_mutex_lock_cred_guard_mutex
      ldv_mutex_lock_3
      <end>
    ldv_mutex_unlock_lock
      ldv_mutex_unlock_2
      <end>
    ldv_mutex_lock_lock
      ldv_mutex_lock_1
      <end>
    ldv_check_final_state
      main
      <end>
    ldv_check_final_state
      main
      <end>
    ldv_check_final_state
      main
      <end>
