Verifying sv/ldv-linux-3.4-simple/43_1a_cilled_true-unreach-call_ok_nondet_linux-43_1a-drivers--usb--storage--ums-datafab.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c
main using GenerateFunctionCallPreprocessor ...
GenerateFunctionCallPreprocessor parents for __VERIFIER_error:
__VERIFIER_error
  ldv_blast_assert
    ldv_check_alloc_nonatomic
    <end>
    ldv_check_alloc_flags_and_return_some_page
    <end>
    ldv_check_alloc_flags
      kmalloc
        datafab_determine_lun
          datafab_write_data
            datafab_transport
              datafab_probe
                main
                <end>
            datafab_transport
              datafab_probe
                main
                <end>
          datafab_read_data
            datafab_transport
              datafab_probe
                main
                <end>
            datafab_transport
              datafab_probe
                main
                <end>
          datafab_id_device
            datafab_transport
              datafab_probe
                main
                <end>
            datafab_transport
              datafab_probe
                main
                <end>
            datafab_transport
              datafab_probe
                main
                <end>
        datafab_write_data
          datafab_transport
            datafab_probe
              main
              <end>
          datafab_transport
            datafab_probe
              main
              <end>
        datafab_read_data
          datafab_transport
            datafab_probe
              main
              <end>
        datafab_id_device
      kzalloc
      ldv_kmem_cache_alloc_16
      <end>
