Verifying sv/ldv-linux-3.4-simple/43_1a_cilled_true-unreach-call_ok_nondet_linux-43_1a-drivers--net--wireless--ath--ath6kl--ath6kl_usb.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c
main using GenerateFunctionCallPreprocessor ...
GenerateFunctionCallPreprocessor parents for __VERIFIER_error:
__VERIFIER_error
  ldv_blast_assert
    ldv_check_alloc_nonatomic
    <end>
    ldv_check_alloc_flags_and_return_some_page
    <end>
    ldv_check_alloc_flags
      kzalloc
        ath6kl_usb_create
          ath6kl_usb_probe
            main
            <end>
        ath6kl_usb_create
          ath6kl_usb_probe
            main
            <end>
        ath6kl_usb_create
          ath6kl_usb_probe
            main
            <end>
      kmalloc
        ath6kl_usb_submit_ctrl_in
          ath6kl_usb_ctrl_msg_exchange
            ath6kl_usb_diag_write32
              main
              <end>
            ath6kl_usb_diag_read32
              main
              <end>
          ath6kl_usb_bmi_read
            main
            <end>
        ath6kl_usb_submit_ctrl_out
          ath6kl_usb_ctrl_msg_exchange
            ath6kl_usb_diag_write32
              main
              <end>
            ath6kl_usb_diag_read32
              main
              <end>
          ath6kl_usb_bmi_write
            main
            <end>
      ldv_pskb_expand_head_27
      <end>
      ldv___netdev_alloc_skb_26
      <end>
      ldv___netdev_alloc_skb_25
      <end>
      ldv_skb_copy_24
      <end>
      ldv_skb_clone_22
      <end>
      ldv_kmem_cache_alloc_16
      <end>
