Verifying sv/ldv-linux-3.4-simple/43_1a_cilled_true-unreach-call_ok_nondet_linux-43_1a-drivers--usb--serial--metro-usb.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c
main using GenerateFunctionCallPreprocessor ...
GenerateFunctionCallPreprocessor parents for __VERIFIER_error:
__VERIFIER_error
  ldv_blast_assert
    ldv_check_alloc_nonatomic
    <end>
    ldv_check_alloc_flags_and_return_some_page
    <end>
    ldv_check_alloc_flags
      kzalloc
        metrousb_startup
          main
          <end>
      ldv_usb_submit_urb_22
        metrousb_unthrottle
          main
          <end>
      ldv_usb_submit_urb_21
        metrousb_open
          main
          <end>
      ldv_usb_submit_urb_20
        metrousb_read_int_callback
          metrousb_read_int_callback
            metrousb_read_int_callback
              metrousb_read_int_callback
                metrousb_read_int_callback
                  metrousb_read_int_callback
                    metrousb_read_int_callback
                      metrousb_read_int_callback
                        metrousb_read_int_callback
                          metrousb_read_int_callback
                            metrousb_open
                              main
                              <end>
                            main
                            <end>
                          metrousb_open
                            main
                            <end>
                          main
                          <end>
                        metrousb_open
                          main
                          <end>
                        main
                        <end>
                      metrousb_open
                        main
                        <end>
                    metrousb_open
                  metrousb_open
                metrousb_open
              metrousb_open
            metrousb_open
      ldv_usb_submit_urb_19
      ldv_kmem_cache_alloc_16
      <end>
