Verifying sv/ldv-linux-3.16-rc1/43_2a_consumption_linux-3.16-rc1.tar.xz-43_2a-drivers--net--ethernet--sun--sungem.ko-entry_point_true-unreach-call.cil.out.c
main using GenerateFunctionCallPreprocessor ...
GenerateFunctionCallPreprocessor parents for __VERIFIER_error:
__VERIFIER_error
  ldv_error
    ldv_check_alloc_nonatomic
    <end>
    ldv_check_alloc_flags_and_return_some_page
    <end>
    ldv_check_alloc_flags
      alloc_skb
        gem_alloc_skb
          gem_rx
            gem_poll
              gem_init_one
                main
                <end>
          gem_init_rings
            gem_reinit_chip
              gem_reset_task
                gem_init_one
                  main
                  <end>
              gem_do_start
                gem_resume
                  main
                  <end>
                gem_open
                  main
                  <end>
              gem_change_mtu
                main
                <end>
                main
                <end>
      ldv_skb_clone_32
      <end>
      ldv_pskb_expand_head_31
      <end>
      ldv_pskb_expand_head_30
      <end>
      ldv___netdev_alloc_skb_29
      <end>
      ldv___netdev_alloc_skb_28
      <end>
      ldv___netdev_alloc_skb_27
        netdev_alloc_skb
          gem_rx
            gem_poll
              gem_init_one
                main
                <end>
      ldv_skb_copy_26
      <end>
      ldv_skb_clone_24
      <end>
      ldv_pskb_expand_head_22
      <end>
      ldv_kmem_cache_alloc_16
      <end>
    ldv__builtin_trap
    <end>
