Verifying sv/ldv-linux-3.16-rc1/43_2a_consumption_linux-3.16-rc1.tar.xz-43_2a-drivers--usb--class--cdc-acm.ko-entry_point_true-unreach-call.cil.out.c
main using GenerateFunctionCallPreprocessor ...
GenerateFunctionCallPreprocessor parents for __VERIFIER_error:
__VERIFIER_error
  ldv_error
    ldv_check_alloc_nonatomic
    <end>
    ldv_check_alloc_flags_and_return_some_page
    <end>
    ldv_check_alloc_flags
      kmalloc
        acm_probe
          main
          <end>
      kzalloc
        acm_probe
          main
          <end>
      ldv_usb_submit_urb_29
        acm_resume
          acm_reset_resume
            main
            <end>
          main
          <end>
      ldv_usb_alloc_urb_28
        acm_probe
          main
          <end>
      ldv_usb_alloc_urb_27
        acm_probe
          main
          <end>
      ldv_usb_alloc_coherent_26
        acm_probe
          main
          <end>
      ldv_usb_alloc_urb_25
        acm_probe
          main
          <end>
      ldv_usb_alloc_coherent_24
        acm_probe
          main
          <end>
      ldv_usb_alloc_coherent_23
        acm_write_buffers_alloc
          acm_probe
            main
            <end>
      ldv_usb_submit_urb_22
        acm_port_activate
      ldv_usb_submit_urb_21
        acm_submit_read_urb
          acm_read_bulk_callback
            acm_probe
            acm_probe
          acm_submit_read_urbs
            acm_resume
              acm_reset_resume
            acm_port_activate
            acm_tty_unthrottle
      ldv_usb_submit_urb_20
        acm_ctrl_irq
      ldv_usb_submit_urb_19
        acm_start_wb
          acm_resume
            acm_reset_resume
          acm_tty_write
      ldv_kmem_cache_alloc_16
      <end>
    ldv__builtin_trap
    <end>
