Verifying sv/ldv-linux-3.16-rc1/43_2a_consumption_linux-3.16-rc1.tar.xz-43_2a-drivers--media--usb--pwc--pwc.ko-entry_point_true-unreach-call.cil.out.c
main using GenerateFunctionCallPreprocessor ...
GenerateFunctionCallPreprocessor parents for __VERIFIER_error:
__VERIFIER_error
  ldv_error
    ldv_check_alloc_flags_and_return_some_page
    <end>
    ldv_check_alloc_nonatomic
      ldv_vzalloc_24
        buffer_init
          main
          <end>
    ldv_check_alloc_flags
      kmalloc
        usb_pwc_probe
          main
          <end>
      kzalloc
        usb_pwc_probe
          main
          <end>
      ldv_kmem_cache_alloc_190
      <end>
      ldv_kmem_cache_alloc_170
      <end>
      ldv_kmem_cache_alloc_150
      <end>
      ldv_kmem_cache_alloc_130
      <end>
      ldv_kmem_cache_alloc_110
      <end>
      ldv_kmem_cache_alloc_90
      <end>
      ldv_kmem_cache_alloc_70
      <end>
      ldv_kmem_cache_alloc_50
      <end>
      ldv_usb_submit_urb_23
        pwc_isoc_init
          start_streaming
            main
            <end>
      ldv_usb_alloc_coherent_22
        pwc_isoc_init
          start_streaming
            main
            <end>
      ldv_usb_alloc_urb_21
        pwc_isoc_init
          start_streaming
            main
            <end>
      ldv_usb_submit_urb_20
        pwc_isoc_handler
          pwc_isoc_init
            start_streaming
              main
              <end>
      ldv_kmem_cache_alloc_16
      <end>
    ldv__builtin_trap
    <end>
